### PR TITLE
Enable warning -duplicate-clear

### PR DESCRIPTION
**Pull request by gares**
Requires Coq >= 8.10

### CODE REVIEW

**Comment by gares** [comment]
It works on master, but not on older versions, since the warning can be silenced in two ways:
- adding a `-` to separate `{X} - X`
- using the new feature `{}X`
I've opted for the second. The former works, but seems like adding noise rather than removing it.
I see only a master branch, that is supposed to compile with all Coq versions.

Looking for advises.

**Comment by Zimmi48** [comment]
Then a third solution is to silence the warning until support for older version of Coq is dropped.

**Comment by gares** [comment]
Thanks! I've opened another PR. This one can stay open, I'll update the header to mention that it requires Coq 8.10

**Comment by anton-trunov** [comment]
The issue has been solved in PR #48 in backward-compatible way (basically I removed those clear switches and refactored the proofs a bit). Thank you, Enrico!

**Pull request closed without merging**
