### PR TITLE
Introduce CI tests.

### PR DESCRIPTION
**Pull request by Zimmi48**
This is a first step, but it's already useful as-is.

For now the build time is about 30 minutes (includes math-comp).
I intend to try avoiding rebuilding math-comp when it is not necessary (when it has not changed and neither has Coq).
Coq itself is not compiled most of the time because we use a binary cache that is populated by Coq CI (the only exception is when Coq has just been updated and the CI hasn't produced the Nix package yet).

I'll open a more general coq-community issue to discuss these caching questions.

### CODE REVIEW

**Comment by anton-trunov** [comment]
> For now the build time is about 30 minutes (includes math-comp).

I think we can reduce the build time by building only math-comp/ssreflect.
It should take around 5 minutes. [This](https://github.com/coq/coq/blob/00b23680d55765d9c681751813ab6e85d41786c5/dev/ci/ci-common.sh#L88) might be useful as it shows how to build only that part of mathcomp.

**Comment by Zimmi48** [comment]
Ah, thanks! I hadn't realized that this was only depending on SSReflect. You should probably update the README to make this explicit: users may be interested to know this as there generally are ssreflect-only packages.

**Comment by anton-trunov** [comment]
Good point! Done in 7c9dde763d13dce7994fcbb31a65fae99eb0a326

**Comment by anton-trunov** [comment]
@Zimmi48 CI looks good! Should I merge?

**Comment by Zimmi48** [comment]
Yes, this is ready from my POV.

**Comment by anton-trunov** [comment]
Thanks a lot!

**Comment by Zimmi48** [comment]
I only think of this now: do you want a Travis badge in the README?

And BTW, since the library is also compatible with Coq master (as demonstrated by Travis), the README could say that the dependency on Coq is 8.8 or higher.

And finally, I've activated a cron job on Travis: it will rebuild the project every day to monitor if an update to Coq breaks it.

**Comment by anton-trunov** [comment]
> I only think of this now: do you want a Travis badge in the README?

Yes, please! How do I get one?

> README could say that the dependency on Coq is 8.8 or higher.

Will do

> it will rebuild the project every day to monitor if an update to Coq breaks it.

Awesome! Thanks.

**Comment by anton-trunov** [comment]
Btw, does CI start every time when I directly push commits? Or is it triggered by opening a PR?

I'm planning to hack on the Coq files, and I guess it's better for me to open a PR as opposed to a direct push so that everything gets tested with CI before getting into master, right?

**Comment by Zimmi48** [comment]
Yes, everything is tested including commits pushed to master, but it's indeed better practice to use a "pull-based" model, that is push to another branch, open a PR, and let CI run before merging.

**Comment by anton-trunov** [comment]
Makes sense, thank you.

**Pull request merged**
