### PR TITLE
CI update: more uniformity and opam package testing.

### PR DESCRIPTION
**Pull request by Zimmi48**
This PR contains several updates to the CI infrastructure:

- update of the Nix setup to take advantage of recent improvements and towards more uniformity (see also the equivalent PR on aac-tactics coq-community/aac-tactics#21), cc @vbgl
- add a test of the opam package using the Docker image by @erikmd (cc @palmskog)

The goal is to add templates in https://github.com/coq-community/manifesto/tree/master/templates based on this setup. That's why I tried to make sure that the two projects had a setup that was as close as possible.

### CODE REVIEW

**Comment by Zimmi48** [comment]
>However, for some reason the "tarball master" build took 30 min or so, which seems excessive (other builds took 2-3 mins). Is this due to intermediate artifacts not being cached? It looks to me like both Coq and ssreflect are being built from scratch in that build. However, if a 30-minute build is the only reasonable way to make this work, I guess that's OK.

This is due to a limitation of the current setup: the Coq master tarball is built in Coq's CI and the binary is uploaded to Cachix. However, if a build starts before this job in Coq's CI finished, then the binary is not available and Coq is rebuilt from source. I intend to document this limitation in an upcoming issue on the state of CI testing with Nix. I have a few ideas of how to solve this which I will detail there.

**Comment by vbgl** [comment]
I’m not sure it makes much sense to test a PR against Coq master (i.e., the state of the Coq development branch at the time when said PR is opened). In particular, in case of failure, you wouldn’t know whether the failure is due to a change in Coq or to the change being evaluated.

If you want to track Coq master, it would make sense to test PRs against the most recent version of Coq that is known to be compatible with this development. In such case you can build Coq only once to a) test this development; and b) test the PRs.

**Comment by erikmd** [comment]
Hi @vbgl
> I’m not sure it makes much sense to test a PR against Coq master

BTW note that the current version of this PR #21 amounts to test compatibility with Coq master twice (once using Nix, which might take ~30mn sometimes with the current setup, and once using Docker+OPAM, with the latest nightly build of Coq).

IMHO it seems important to me to know whether the PRs, once merged, will be compatible with master (even if the issue comes from a change in Coq), in order to be prepared early to fix this, rather than discovering this only at the branch build after the merge…

> In particular, in case of failure, you wouldn’t know whether the failure is due to a change in Coq or to the change being evaluated.

Indeed, but if we want to make this difference explicit, maybe one could add a special Travis CI job such as:
```
if [ $TRAVIS_EVENT_TYPE = "pull" ]; then
  git checkout $TRAVIS_BRANCH  # or so (checkout the target branch without the PR changes)
  make
fi
```
so if that job doesn't fails, but the other job using Coq master fails, it would be due to the PR changes.

But you might find this suggestion a bit exotic :), as I've not seen other repos using one such "witness" job.

> If you want to track Coq master, it would make sense to test PRs against the most recent version of Coq that is known to be compatible with this development. In such case you can build Coq only once to a) test this development; and b) test the PRs.

Good idea; but this could be more difficult to implement/maintain than the current version of #21?
(IINM this approach might be implemented using a specific cached Nix build, and a commit reference somewhere in the plugin repo? but in this case one should frequently update that commit reference, which would be not very practical to maintain, maybe.)

My 2 cents, Erik

**Comment by vbgl** [comment]
On 23/11/2018 09:56, Erik Martin-Dorel wrote:
> IMHO it seems important to me to know whether the PRs, once merged, will be compatible with master

The thing is that you don’t know this. Indeed, Coq master may have
arbitrarily changed between the testing of the PR and its merging.

What I mean is that you should not care too much about the
“bleeding-edge” version of Coq, as this status expires fast.

I understand that you want to test against a recent version (in the
spirit of what is done in the Docker setting). The data-race that
prevents reusing a cached build comes from the attempt to build against
the most recent version of Coq (which, again, is not the same as some
recent version).

@Zimmi48 Would it make sense to have some kind of “Coq channel” which
tracks recent versions of Coq for which a cached build is available?
E.g., instead of fetching sources from
“github.com/coq/coq/tarball/master” one could get them from
“…/coq-channel/tarball/master” or first fetch the relevant commit hash
and then fetch sources from this commit. Pushing that channel could be
done at the end of CI builds of Coq.

**Comment by Zimmi48** [comment]
@vbgl Your remark goes beyond the scope of this PR which is not changing anything in terms of the versions of Coq we are testing. Note that there is already a cron job running every day to test compatibility with the latest Coq version so it should be quite rare in practice to fall in the case you describe, but of course, this CI only gives an approximate answer, not a definite one. Now, if a PR fails on Coq master and it looks unrelated to the PR itself, it's always possible to relaunch a new test on the project master branch to see if it is also failing (even if the last cron test was succeeding).

Regarding your suggestion of a Coq channel, yes this is one of the two options I was about to propose to solve the long build time issue that was raised by @palmskog and @erikmd. This is also independent of the present PR which does not change anything in this respect.

Regarding the point made by @erikmd that we are testing twice the build with Coq master, yes this is true indeed. The Docker setup is unfortunately required to test the opam file without rebuilding Coq, even if it is way more complex than the Nix setup. On the other hand, I am reluctant to ditch the Nix setup which is superior in many aspects (at least from my perspective). Anyways, I'm intending to document all of this soon, so it should be able to do a comparison opam / opam + Docker / Nix + Cachix.

**Comment by erikmd** [comment]
@Zimmi48
> The Docker setup is unfortunately required to test the opam file without rebuilding Coq, even if it is way more complex than the Nix setup.

If I may add a small note about this: I agree the Docker config (in `.travis-ci.yml`) is indeed more verbose than the overall Nix config (in `.travis-ci.yml` + `default.nix`) but as most of the LoC in this Docker config are bash commands, they could be more easily refactored by developers not familiar with Nix; and moreover many LoC here are optional-but-useful commands (to print metadata or improve the layout of Travis CI logs (or just show one can use the `TRAVIS_EVENT_TYPE` variable)).

BTW you may want to implement here the change I suggested [in coq-community/manifesto#23](https://github.com/coq-community/manifesto/pull/23/files#r235975359)?
Namely, adding `opam install -y -j ${NJOBS} --deps-only .` after `opam update -y`.

> I'm intending to document all of this soon, so it should be able to do a comparison opam / opam + Docker / Nix + Cachix.

:+1:

**Comment by Zimmi48** [comment]
>BTW you may want to implement here the change I suggested in coq-community/manifesto#23?
Namely, adding opam install -y -j ${NJOBS} --deps-only . after opam update -y.

Updated.

**Comment by Zimmi48** [comment]
Following up on the discussion on testing a version that is known to build fine, I have added a section to the documentation of the CI with Nix about commit pinning: https://github.com/coq-community/manifesto/wiki/Continuous-Integration-with-Nix#pinning-the-tested-development-version.
This is a case of a clear advantage of the Nix setup BTW. I used it in coq-community/atbr#3 to make sure that the CI was correctly set up and the only issue was that the package was not building with the latest development version of Coq. (Maybe I could have done the same with the Docker build but it would require digging the right Docker image hash, whereas in the Nix case, it is just a commit hash from the Coq repository.)

**Comment by erikmd** [comment]
@Zimmi48 indeed that's very nice to be able to pin a specific commit of Coq for Nix builds!

> Maybe I could have done the same with the Docker build but it would require digging the right Docker image hash,

Yes in theory one could achieve something similar with Docker images, but unfortunately not with the currently implemented infrastructure of Docker-Coq, as only one `coqorg/coq:dev` image is kept in https://hub.docker.com/r/coqorg/coq/ (the latest nightly build).

To sum up, if we want to compare Docker-Coq with the Nix CI infrastructure, I see mainly 3 advantages:
1. Docker-Coq provides an opam2 environment with Coq pre-built (and "sudo apt-get" available)
2. Coq is pre-built using two different compilers, currently both 4.05.0 and 4.07.0+flambda (I'd say this could be useful especially for plugin developers or benchmarks, but maybe you have other applications in mind for this aspect ?)
3. Docker-Coq may be more easy to setup for projects built on GitLab CI, given its native Docker support, while Travis CI is more "Docker-agnostic"
    (in particular, the conf file [docker-coq-gitlab-ci-demo-1/.gitlab-ci.yml](https://gitlab.com/erikmd/docker-coq-gitlab-ci-demo-1/blob/master/.gitlab-ci.yml) appears to be less cumbersome than its Travis CI counterpart)

BTW @Zimmi48 do you confirm the cached Nix builds are only available with one version of OCaml? (according to the log https://travis-ci.com/coq-community/lemma-overloading/jobs/160545280 it seems it is currently `ocaml-4.06.1`)

**Comment by Zimmi48** [comment]
Indeed, I do confirm this. It would be nice to add this comparison to a page of the wiki :wink:

**Comment by erikmd** [comment]
@Zimmi48
> It would be nice to add this comparison to a page of the wiki wink

Good idea :slightly_smiling_face: So I've pasted that comparison (and extended it a bit more) in that paragraph of the wiki:
https://github.com/coq-community/manifesto/wiki/Continuous-Integration-with-Nix#alternative-setup-and-comparison
(Feel free to proofread, refine or extend that prose)
Kind regards, Erik

**Comment by Zimmi48** [comment]
Looks great. Thanks for writing this!

**Pull request merged**
