### PR TITLE
Switch from Travis CI to GitHub Actions.

### PR DESCRIPTION
**Pull request by Zimmi48**
See https://coq.zulipchat.com/#narrow/stream/237663-coq-community-devs.20.26.20users/topic/New.20Travis.20limits.2E for context.

### CODE REVIEW

**Comment by Zimmi48** [comment]
Given the rate at which we are burning our free Travis credits, Travis will soon stop to run any build. So I'm merging this PR without further delay.

**Comment by anton-trunov** [comment]
@Zimmi48 Thank you very much for taking care of this. Sorry for not being reactive due to `EmailOverflow` error.

**Comment by Zimmi48** [comment]
Yeah no worries. We are many to be facing this issue :wink: Though in my case, I've stopped receiving GitHub e-mails and use the web notifications instead, so I have two errors in parallel, the standard `EmailOverflow` and the `NotificationOverflow`.

**Comment by anton-trunov** [comment]
That's a good one :) Thanks for the pointer to web notification, I should look into that.

**Comment by Zimmi48** [comment]
It's a pretty powerful tool. It works like an inbox, where you can archive, mute, mark as unread and save your notifications.

**Comment by anton-trunov** [comment]
Is it https://octobox.io or GitHub included the support for this out-of-the-box?

**Comment by Zimmi48** [comment]
Sorry I missed this comment. You do not need Octobox anymore. GitHub have taken all the useful features to improve their web notification system. Octobox is more or less unmaintained now.

**Pull request merged**
